export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const GET_POST = 'GET_POST';
export const GET_POST_PENDING = 'GET_POST_PENDING';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';