export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const GET_POSTS = 'GET_POST';
export const GET_POSTS_PENDING = 'GET_POST_PENDING';
export const GET_POSTS_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POST_REJECTED';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';