export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING'; 
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_FULFILLED = 'GET_POSTS_FULFILLED';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';

export const GET_POST = 'GET_POST';
export const GET_POST_PENDING = 'GET_POST_PENDING';
export const GET_POST_FULFILLED =  'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';

export const GET_POSTS_COMMENT = 'GET_POSTS_COMMENT';
export const GET_POSTS_COMMENT_PENDING = 'GET_POSTS_COMMENT_PENDING';
export const GET_POSTS_COMMENT_FULFILLED = 'GET_POSTS_COMMENT_FULFILLED';
export const GET_POSTS_COMMENT_REJECTED = 'GET_POSTS_COMMENT_REJECTED';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_PENDING = 'ADD_COMMENT_PENDING';
export const ADD_COMMENT_FULFILLED = 'ADD_COMMENT_FULFILLED';
export const ADD_COMMENT_REJECTED = 'ADD_COMMENT_REJECTED';